### ISSUE TITLE
Working only when red links don't have a custom anchor (piped link)

### ISSUE THREAD

**Issue by NicolasNallet** [marohh/mediawikiRemoveRedlinks#1]
it's ok when red links are like 
`[[a red link]]`
but when one link has piped text like
`[[a red link|different text]]`
All red links become red again.

**Comment by marohh** [comment]
Thanks for testing and feedback. 
This turned out to be more complex than originally expected. 
I've applied a fix which solves that behavior according to my test. 
However, it is additionally required to switch off the parser cache by
 $wgParserCacheType = CACHE_NONE;
otherwise, a previously rendered result will be persistent.

**Comment by marohh** [comment]
Closing this issue as solved with the latest version after further tests.

**Comment by marohh** [comment]
Just to notify that the requirement "$wgParserCacheType = CACHE_NONE;" introduced above 
is solved and no longer required. 

see closed issue: 
https://github.com/marohh/mediawikiRemoveRedlinks/issues/3

**Comment by NicolasNallet** [comment]
Thanks a lot !
