### ISSUE TITLE
impact of page cache  // was: Heavily broken

### ISSUE THREAD

**Issue by thecutefinder** [marohh/mediawikiRemoveRedlinks#9]
See https://phabricator.miraheze.org/T10310

**Comment by marohh** [comment]
I don't really get the actual issue described in the thread.

- Logged in vs logged out users:  The extension is intended for sites with a "read-only" mode for logged out users, so removing redlinks only works for logged out users. -- 
- Caching behavior: This extension does not disable caching in order not to impact site performance. 

However, the extension is not regularly tested with against updated mediawiki versions.

**Comment by thecutefinder** [comment]
Ah, the site in which I intend to use it is designed to be editable by anyone, but I want to either remove redlinks or add rel=nofollow to them when users are logged out for SEO purposes (having Google navigate to a URL that it will then be told is noindex is a bad idea, because Google only crawls a set amount of URLs per site).

The intended purpose of removing redlinks for logged-out users has not worked on https://genshinimpact.miraheze.org unless an edit or purge action is made by a logged out user.

**Comment by marohh** [comment]
For the page caching question: For standard installations  the page cache should be automatically purged when the site's LocalSettings.php is edited.  Compare: https://www.mediawiki.org/wiki/Manual:$wgInvalidateCacheOnLocalSettingsChange --- default: true

Since modifying the LocalSettings.php is mandatory for installation,  I'd expect the installation procedure to force purging the cache. This might potentially be different if additional caching mechanism beyond mediawiki are used. Also the browser's local cache (when just testing on a single computer) may serve an old version of the page even though the server cache has been purged.

**Comment by thecutefinder** [comment]
In the case of Miraheze, LocalSettings is not directly modified when extensions are changed, because all wikis share the same codebase and can enable/disable extensions freely. I'm unsure of the exact setup beyond that, you'd have to see Miraheze's GitHub. This may be a Miraheze-specific issue.
